### ISSUE TITLE
Error: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

### ISSUE THREAD

**Issue by PoLaKoSz** [GrepoDataTools/grepodata-backend#55]
**Describe the bug**
Town intelligence window crashes when the town name contains non Latin1 characters (for example `Őrbottyán`).

**To Reproduce**
Insert the following snippet to the `Software/Application/Indexer/indexer.js`:
```diff
  function loadCityIndex(globals) {
+      var officialHash = 'eyJpZCI6NjQxMDksIml4Ijo1NzQsIml5Ijo2NzUsInRwIjoiZ2hvc3RfdG93biIsIm5hbWUiOiJcdTAxNTByYm90dHlcdTAwZTFuIn0';
+      var json = decodeHashToJson(officialHash);
+      console.log(json);
+      var hash = encodeJsonToHash(json); // Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
```

**Expected behavior**
JavaScript renders Town intelligence window without any problem.

**Screenshots**
![GrepoData-bug](https://github.com/user-attachments/assets/eec07f2b-1a99-4c27-b750-395a05c373d2)

**Additional context**
```
Error: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
   at encodeJsonToHash
   at getTownHash
   at renderTownIntelWindow
```

**Comment by CamielK** [comment]
Thanks for your detailed report! Will fix asap
